namespace Auth.Api.Models.Messages
{
    /// <summary>
    /// Published by Auth.Api after a patient rotates their PatientMasterKey
    /// (the AES-256 key used to encrypt all their medical documents).
    ///
    /// Consumed by Users.Api, which updates its own local copy and then
    /// fans this event out to AccessRequests.Api, MedicalData.Api, and
    /// Diagnostics.Api — mirroring the same propagation path used for
    /// UserData / IdentityCreatedEvent at registration time.
    ///
    /// Only ever emitted for Patients: other roles don't hold a personal
    /// AES key, they recover a patient's key via an access envelope instead.
    /// </summary>
    public class AesKeyRotatedEvent
    {
        /// <summary>
        /// The identity id (Auth.Api's ApplicationUser.Id) of the patient
        /// whose key was rotated. Used by Users.Api to find the matching
        /// IdentityId on its own Patient record.
        /// </summary>
        public required string IdentityId { get; set; }

        /// <summary>
        /// The user id (Guid, originally generated by Users.Api when the
        /// Patient record was created, and echoed back to Auth.Api via
        /// UserCreatedResponseEvent at registration time). This is the id
        /// AccessRequests.Api, MedicalData.Api, and Diagnostics.Api use to
        /// key their own denormalized User copies — they never saw
        /// IdentityId, so this is what lets them find the right row.
        /// </summary>
        public required Guid UserId { get; set; }

        /// <summary>
        /// The new PatientMasterKey, ECIES-encrypted client-side with the
        /// patient's own EccPublicKey. Replaces the previous EncryptedAesKey
        /// everywhere it's stored.
        /// </summary>
        public required string EncryptedAesKey { get; set; }
    }
}