// <auto-generated />
using System;
using Diagnostics.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Diagnostics.Api.Migrations
{
    [DbContext(typeof(DiagnosticsDbContext))]
    [Migration("20260617211211_Diagnostics Migration")]
    partial class DiagnosticsMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Diagnostics.Api.Models.Domain.DiagnosticDraft", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("CompletedByDoctorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("CreatedByAssistantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("EncryptedData")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Iv")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LinkedMedicalRecordIds")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("PatientId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("PatientWalletAddress")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("PatientId");

                    b.ToTable("DiagnosticDrafts");
                });

            modelBuilder.Entity("Diagnostics.Api.Models.Domain.DiagnosticDraftEnvelope", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("DiagnosticDraftId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("EncryptedAesKey")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("DiagnosticDraftId", "UserId")
                        .IsUnique();

                    b.ToTable("DiagnosticDraftEnvelopes");
                });

            modelBuilder.Entity("Diagnostics.Api.Models.Domain.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WalletAddress")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Diagnostics.Api.Models.Domain.DiagnosticDraft", b =>
                {
                    b.HasOne("Diagnostics.Api.Models.Domain.User", "Patient")
                        .WithMany()
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("Diagnostics.Api.Models.Domain.DiagnosticDraftEnvelope", b =>
                {
                    b.HasOne("Diagnostics.Api.Models.Domain.DiagnosticDraft", "DiagnosticDraft")
                        .WithMany("Envelopes")
                        .HasForeignKey("DiagnosticDraftId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DiagnosticDraft");
                });

            modelBuilder.Entity("Diagnostics.Api.Models.Domain.DiagnosticDraft", b =>
                {
                    b.Navigation("Envelopes");
                });
#pragma warning restore 612, 618
        }
    }
}
